### ISSUE TITLE
Subtitles Events

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#10]
**Is your feature request related to a problem? Please describe.**

When adding/removing an external subtitles file - no event is fired for itemadded/itemremoved - this maybe an emby thing not sure
itemupdated does fire for both removal and addition - but the reason "None, MetadataImport" is not meaningful - but again an emby thing i suspect
So i guess what i am asking is - does emby report on subs being added/removed or not?

**Comment by AnthonyMusgrove** [comment]
Hi mate, I've been looking into this one.  There's a Subtitle Manager with two events I can link into, I've added them and tested downloading subtitles and it isn't yet working, so I'm escalating it to the Emby Team to find out if the ISubtitleManager is actually still being used.  It shouldn't be too much longer on this one :)

**Comment by Penkethboy** [comment]
there maybe two things here
1) downloading via a plugin - not what i was think of but needs covering.
2) adding manually a srt file (usually i extract the forced srt file from a movie/episode) then add it to emby at a different time to the movie/episode.

2) is the one i'm interested in :)
@anthonymusgrove
