### ISSUE TITLE
Add Confirmation Button for deleting an Action

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#11]
**Is your feature request related to a problem? Please describe.**

Could we have a comfirmation dialog for when you hit the delete button on an event
To prevent the ******* issue i just had when i clicked it by mistake

**Comment by AnthonyMusgrove** [comment]
I've checked out the alerts functions in the dashboard, I'll get this in for the next release! :)

**Comment by Penkethboy** [comment]
Just tested this with 2.3 and it does not show an alert

**Comment by AnthonyMusgrove** [comment]
Now added for the next release mate :)  - So what happens?  If you hit the delete button, both the edit and delete buttons disappear, and a confirmation is displayed, where you can either click Really Delete? or Cancel, it works really well, and will be in the next release, 2.3.1! per image:  

![really_delete_confirmation](https://user-images.githubusercontent.com/55648663/81473884-191dbf00-9245-11ea-9472-6a62e230367c.png)
