### ISSUE TITLE
New Event - New recording created

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#14]
When you add a new recording (manually) to LiveTV and/or a new recording is added to a (an Existing) Series recording - i guess after the EPG is updated.

**Describe the solution you'd like**
A new event, time/date for when the start end of the recording will occur, Name, Series, Season, Episode, name of recording, channel number, Library name etc

**Describe alternatives you've considered**
Reading the recording events periodically via the API - and reporting on them - clunky but works

**Comment by AnthonyMusgrove** [comment]
Great idea mate, absolutely perfect idea.   And easy to implement too, there are events in the system for Timer creation and Series Timer creation, bare with me I'll get some of the variables available for these events, and we can integrate new events in for them :)

**Comment by Penkethboy** [comment]
Cool

**Comment by AnthonyMusgrove** [comment]
Alrighty!  Issue #14 is complete, i've added two new events:

 

onRecordingTimerCreated and onRecordingTimerCancelled :)

 

Recording Timer CREATED : Timer ID:"0684a592ea448fbe53bf240a44a1a4dc" - Name:"300", Date_Start:"22/06/2020 8:30:00 PM", Date_End:"22/06/2020 10:55:00 PM" 
Recording Timer CANCELLED : Timer ID:"0684a592ea448fbe53bf240a44a1a4dc" - Name:-, Date_Start:-, Date_End:-
