### ISSUE TITLE
Change name of OnScheduledTask

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#16]
**Is your feature request related to a problem? Please describe.**
A suggestion - we have three scheduled Task events now - so could be a tad confusing

**Describe the solution you'd like**
Maybe change this to onScripterXScheduledTask to make it clearer its for the ScripterX scheduled task in the scheduled Tasks section of Emby

![5ea8154aeb655_Annotation20200428123452](https://user-images.githubusercontent.com/21155304/80861397-3b707500-8c66-11ea-9dac-edf1cc4c5351.jpg)

**Additional context**
I noticed you removed the description about the event - not sure if this is intentional or not as it gave a good indication of what it was for.

Some Event ideas i had a few days ago

1 Name of Task

2Time taken

3 Status - i.e. Completed/Failed/Aborted etc - if its available -> Manual (user) start rather than on a schedule

When it last ran before - if that's available after you get the event?

**Comment by AnthonyMusgrove** [comment]
Changed name of onScheduledTask to onScripterXScheduledTask
Re-added note regarding the explanation for this event

The variables suggested will be transferred to onScheduledTaskStart/Stop :)
