### ISSUE TITLE
Return of Enable ScripterX

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#17]
**Is your feature request related to a problem? Please describe.**
In early versions of the plugin there was a checkbox to turn the plugin off

**Describe the solution you'd like**
Could it make a return? Would be handy to save having to delete stuff from the plugin page.

![5e8de4f5be2bd_Annotation20200408154953](https://user-images.githubusercontent.com/21155304/80861979-99528c00-8c69-11ea-8891-2af62aa36474.jpg)

**Comment by AnthonyMusgrove** [comment]
- Added checkbox to each event to enable or disable that event (which will enable or disable all actions within that event)

![image](https://user-images.githubusercontent.com/55648663/81187140-fb5b1a80-8ff6-11ea-9e56-c9faa0d848e3.png)
