### ISSUE TITLE
Variables are Case Sensitive

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#18]
**Describe the bug**
%item.name% works but %item.Name% does not - returns %item.Name%

**Expected behavior**
If the variables need to be case sensitive then needs to be in the user notes.
or
the variables could be case insensitive?

**Additional context**
Tested on v2.2.6 (windows) but been this way since the initial versions.

it's not a big issue just catches you out occasionally.
The Test button will help with this :)

**Comment by AnthonyMusgrove** [comment]
This one has now been resolved!  In the next version release, all tokens will be case-INsensitive.  So %item.id%, %Item.ID%, %ItEM.iD% etc will work!
