### ISSUE TITLE
Version Variable

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#19]
**Is your feature request related to a problem? Please describe.**
As we are going through multiple versions of ScripterX at the moment

**Describe the solution you'd like**
Could we have a variable with the ScripterX version number - that applies to all events - don't think you need to add this to the interface UI - as likely this will only be needed occasionally and once the code is mature is likely not going to be used much.

**Additional context**
The reason is that when we have an issue like %item.library.name% working sometimes and not others - tracking which version did or did not work - would be a lot simpler if we had a version variable we could add to the script logs.

**Comment by AnthonyMusgrove** [comment]
Added the following, with examples:

**%scripterx.version%**     2.2.6.0
**%scripterx.version.major%**     2
**%scripterx.version.minor%**     2
**%scripterx.version.revision%**     6
**%scripterx.version.build%**     0

This will be released in v2.2.7.0
