### ISSUE TITLE
Please publish the source code rather than the compiled dll file

### ISSUE THREAD

**Issue by gardar** [AnthonyMusgrove/Emby-ScripterX#21]
Please publish the source code rather than just the compiled dll file.
It would also be good if the git commits included a meaningful message.

**Comment by AnthonyMusgrove** [comment]
We have no plans on releasing the source code as there will be premium features in the near future that may require authentication and handshaking for licencing/registration. To minimise the ability of theft and piracy, our business decision was to licence this Plugin as proprietary.

However, we are open to external developers helping with the project - by all means if you're interested we will have external developer applications opening soon; We've got a few Plugin projects in the pipeline that will require some intense research and development.

Regards,

Anthony
