### ISSUE TITLE
ip address variable for onAuthentication* events

### ISSUE THREAD

**Issue by nayrnet** [AnthonyMusgrove/Emby-ScripterX#22]
As a Emby Admin I wish to pass through the user IP as a %ip% variable onAuthenticationFailed events so I can script up blocking at the edge firewall after too many failed login attempts.

**Comment by AnthonyMusgrove** [comment]
This is a great idea, leave it with me! :)

**Comment by AnthonyMusgrove** [comment]
Update:  Just waiting on some information from Emby Dev team regarding the RemoteEndPoint data for the AuthenticationRequest (having an issue accessing the property: System.MissingMethodException: System.MissingMethodException: Method not found: 'System.String MediaBrowser.Controller.Session.AuthenticationRequest.get_RemoteEndPoint()'.)  .. Will update you as soon as I get it working :)

**Comment by AnthonyMusgrove** [comment]
Bingo, got it.

2020-05-17 17:19:57.803 Info Emby ScripterX: onAuthenticationFailed: Anthony sadgasdfasdf "Chrome" 192.168.1.124

It will be available in the next release as %device.remote.ipaddress%
:)

**Comment by AnthonyMusgrove** [comment]
It will also be available for onAuthenticationSucceeded !

**Comment by AnthonyMusgrove** [comment]
This is now available mate, and released into the catalog!  See the token list under Authentication Succeeded & Failed.  For more info: https://github.com/AnthonyMusgrove/Emby-ScripterX/blob/master/README.md
