### ISSUE TITLE
onLibraryScanComplete - add scan result

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#23]
**Is your feature request related to a problem? Please describe.**
Can you add %task.result% - probably as %scan.result% to the lib scan complete event as its missing

**Describe the solution you'd like**
task.result exists for onScheduledTaskEnded - can this be added to lib scan complete

As a replacement for issue 4

**Comment by AnthonyMusgrove** [comment]
Thank you mate I'll check this one out, Im hoping it's possible because that would make a lot of sense :)

**Comment by AnthonyMusgrove** [comment]
RE Issue #24, the best I can do so far is add an %was.cancelled% token to onLibraryScanComplete.  There isn't much information provided at this stage, so I'm still investigating on whether or not it is possible to get additional failedstates for library scanning.  Try using the %was.cancelled% token and let me know if its 'true' if there is a scanning error (I'm very curious on how this will behave)

 

thanks mate!

![was_cancelled](https://user-images.githubusercontent.com/55648663/85289477-dead7000-b4da-11ea-9657-efa02f0175b2.png)
