### ISSUE TITLE
audio transcode etc parameters not in 2.3.7/8

### ISSUE THREAD

**Issue by Penkethboy** [AnthonyMusgrove/Emby-ScripterX#27]
%transcoding.height%,%transcoding.audio.channels%,%transcoding.audio.codec%,%transcoding.bitrate%,%transcoding.container%,%transcoding.framerate%,%transcoding.reasons%

are not available in onplaybackprogress

**Comment by AnthonyMusgrove** [comment]
Thank you mate, investigating this one now :)

Confirmed issue:
2020-05-30 11:11:32.122 Info Emby ScripterX: onPlaybackProgress: %transcoding.height%,%transcoding.audio.channels%,%transcoding.audio.codec%,%transcoding.bitrate%,%transcoding.container%,%transcoding.framerate%,%transcoding.reasons%

**Comment by AnthonyMusgrove** [comment]
This one is now resolved mate, and will be available in the next release :)

2020-05-30 11:17:38.156 Info Emby ScripterX: onPlaybackProgress: 480,2,mp3,2032128,ts,125,ContainerNotSupported

Achieved with:

![onPlaybackProgress_ResolvedTranscoding](https://user-images.githubusercontent.com/55648663/83316110-7797f500-a267-11ea-831d-2e12db77bb0b.png)

**Comment by AnthonyMusgrove** [comment]
Fix is now up for this one mate, v3.0.1 :)

**Comment by Penkethboy** [comment]
![Annotation 2020-05-30 155855](https://user-images.githubusercontent.com/21155304/83331462-80e88800-a28e-11ea-961a-f6c6547cb96c.jpg)

Hi
I am seeing the new transcode parameters but could they be with the other older transcode parameters rather than in two sets as they have the same colour etc
