### ISSUE TITLE
Create proper documentation & wiki for Packages

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#33]
**Is your feature request related to a problem? Please describe.**
The Packages functionality requires a proper wiki and proper documentation for its functionality and usability.

**Describe the solution you'd like**
A clear, concise wiki and documentation for Packages

@Slugger

**Comment by Slugger** [comment]
Can you provide some quick details on how I can create the package config interface?  And also how I access those config options within my js?  Thanks.

**Comment by AnthonyMusgrove** [comment]
Hey mate, of course, this is the page I've put together so far:  https://wiki.emby-scripterx.info/books/packages/page/getting-started

**Comment by AnthonyMusgrove** [comment]
Almost done mate :)

![Package config debug](https://user-images.githubusercontent.com/55648663/84503159-00e60780-acfd-11ea-869a-f587e8b7958b.png)

**Comment by AnthonyMusgrove** [comment]
Almost there!

![Save Config 2](https://user-images.githubusercontent.com/55648663/84561210-d85a1e00-ad8d-11ea-8c72-fb9e2b2d4941.png)

**Comment by AnthonyMusgrove** [comment]
Now saves to config xml :)

![Settings XML](https://user-images.githubusercontent.com/55648663/84561540-97173d80-ad90-11ea-84bb-194968fdd238.png)

**Comment by AnthonyMusgrove** [comment]
`	var test_Setting_value = ScripterX.Config.Get("testSetting2").StringValue();

	ScripterX.Log.Info("Value from config: " + test_Setting_value);

	ScripterX.Config.Set("testSetting2", "Test 1 2 3");

	var test_Setting_value2 = ScripterX.Config.Get("testSetting2").StringValue();

	ScripterX.Log.Info("Value from config after setting: " + test_Setting_value2);
`

Yields:

`2020-06-13 20:46:54.322 Info Emby ScripterX: 8b91c4d0-66f2-47c8-9471-ae9c741d6b6f: Value from config: Test 2
2020-06-13 20:46:54.323 Debug XmlSerializer: Serializing to file C:\Users\Anthony\AppData\Roaming\Emby-Server\programdata\data/ScripterX/Packages/8b91c4d0-66f2-47c8-9471-ae9c741d6b6f/PackageConfig.xml
2020-06-13 20:46:54.325 Info Emby ScripterX: 8b91c4d0-66f2-47c8-9471-ae9c741d6b6f: Value from config after setting: Test 1 2 3`

**Comment by AnthonyMusgrove** [comment]
https://wiki.emby-scripterx.info/books/packages/page/package-configuration

Just waiting for the Emby Team to fix the Plugin Portal so I can upload the new version to the catalog, however I've uploaded it here on github so you can manually copy it and use it until then.

:)

**Comment by AnthonyMusgrove** [comment]
Now live on the catalog v3.0.4  :)

**Comment by Slugger** [comment]
Is a `ScripterX.Web` just a proxy to some class in .Net Core?  If so, can you point me to the api docs for the interface?  Basically, I'm looking for additional features: customize headers mainly, but also if there's anything else that might be available.  Basically the web service I plan on posting to expects the content-type to be application/json.  Just trying to figure out if this is possible.

**Comment by AnthonyMusgrove** [comment]
Absolutely mate, at its essence, it is a proxy to an IHttpClient, I can expose all the functionality to truly customise it :) let me take a look right now.

**Comment by AnthonyMusgrove** [comment]
It accepts an HttpRequestOptions object to customise the request, available is:

`        public bool LogResponse { get; set; }
        public bool LogResponseHeaders { get; set; }
        public bool LogErrorResponseBody { get; set; }
        public bool EnableKeepAlive { get; set; }
        public CacheMode CacheMode { get; set; }
        public TimeSpan CacheLength { get; set; }
        public bool LogErrors { get; set; }
        public int TimeoutMs { get; set; }
        public bool AppendCharsetToMimeType { get; set; }
        public string DownloadFilePath { get; set; }
        public string LogUrl { get; set; }
        public bool SingleTcpConnection { get; set; }
        public IDisposable ConnectionContext { get; set; }
        public FileShareMode FileShareMode { get; set; }
        public bool EnableDefaultUserAgent { get; set; }
        public bool LogRequestAsDebug { get; set; }
        public bool LogRequest { get; set; }
        public bool BufferContent { get; set; }
        //
        // Summary:
        //     Gets or sets the URL.
        //
        // Value:
        //     The URL.
        public string Url { get; set; }
        public CompressionMethod? DecompressionMethod { get; set; }
        //
        // Summary:
        //     Gets or sets the accept header.
        //
        // Value:
        //     The accept header.
        public string AcceptHeader { get; set; }
        //
        // Summary:
        //     Gets or sets the cancellation token.
        //
        // Value:
        //     The cancellation token.
        public CancellationToken CancellationToken { get; set; }
        //
        // Summary:
        //     Gets or sets the user agent.
        //
        // Value:
        //     The user agent.
        public string UserAgent { get; set; }
        //
        // Summary:
        //     Gets or sets the referrer.
        //
        // Value:
        //     The referrer.
        public string Referer { get; set; }
        public FileOpenOptions FileOpenOptions { get; set; }
        //
        // Summary:
        //     Gets or sets the host.
        //
        // Value:
        //     The host.
        public string Host { get; set; }
        //
        // Summary:
        //     Gets or sets a value indicating whether [enable HTTP compression].
        //
        // Value:
        //     true if [enable HTTP compression]; otherwise, false.
        public bool EnableHttpCompression { get; set; }
        public Dictionary<string, string> RequestHeaders { get; }
        public string RequestContentType { get; set; }
        public ReadOnlyMemory<char> RequestContent { get; set; }
        public ReadOnlyMemory<byte> RequestContentBytes { get; set; }
        public HttpContent RequestHttpContent { get; set; }
        //
        // Summary:
        //     Gets or sets the progress.
        //
        // Value:
        //     The progress.
        public IProgress<double> Progress { get; set; }
        public bool EnableAutomaticTimeouts { get; set; }

        public void SetPostData(IDictionary<string, string> values);`

**Comment by AnthonyMusgrove** [comment]
And my apologies, I haven't yet documented but Web also has JsonPost,

JsonPost(string url, string data)

which sets the content type as well to "application/json"

Currently, string data is just a JSON string, but I can add to this the ability to specify a JSON object, rather than JSON.stringify()'ing your json object first :)

**Comment by AnthonyMusgrove** [comment]
How does this look for header customisation?

`var custom_headers = ScripterX.Web.CustomHeaderBuilder();
 custom_headers.add("Content-Type", "application/json");
 custom_headers.add("Accept", "application/json");
 
ScripterX.Web.JsonPost("http://192.168.1.10/hook.php", "test", custom_headers);`

`2020-06-16 20:31:03.404 Debug Emby ScripterX: Custom Header Specified: Key=Content-Type, Value=application/json
2020-06-16 20:31:03.404 Debug Emby ScripterX: Custom Header Specified: Key=Accept, Value=application/json
2020-06-16 20:31:03.407 Info HttpClient: POST http://192.168.1.10/hook.php`

**Comment by AnthonyMusgrove** [comment]
I also fixed the Web.Get() to return the content received on Get;

	var testget = ScripterX.Web.Get("http://192.168.1.10/");
	ScripterX.Log.Debug("Get from Website: " + testget);

2020-06-16 21:06:58.089 Info HttpClient: GET http://192.168.1.10/
2020-06-16 21:06:58.104 Debug Emby ScripterX: 8b91c4d0-66f2-47c8-9471-ae9c741d6b6f: Get from Website: <!DOCTYPE html>
<html><head><title>MediusWeb</title></head>
<body>MediusWeb, Welcome.</body>
</html>

**Comment by AnthonyMusgrove** [comment]
Get, JsonPost, Post all now support the custom headers parameter.

**Comment by Slugger** [comment]
This is all good.  Just having the `JsonPost()` method is probably going to cover all of my needs, actually.  I just can't stress enough how important the docs are going to be for this to be adopted by developers with some moderately complicated ideas/use cases.

Even here, had I known about `JsonPost()` being available, I wouldn't have asked for the custom headers functionality.  (Now with that said, custom headers is very useful anyways so definitely not a waste, but wouldn't have been a priority if I had known about `JsonPost()`).

And then this new custom headers feature.  I need to create a `CustomHeaderBuilder`, populate that and then pass it as an arg.  That's fine, but the docs need to have all of this info.

Very grateful for the additions, testing this `JsonPost()` along with the context token map right now!

**Comment by Slugger** [comment]
Looks like I have to pass the 3rd arg to JsonPost, even if I don't have any custom headers.  An overloaded version of JsonPost() that only requires the first two args would be nice.  Passing null as the 3rd arg causes a null pointer exception.  I had to create an empty builder and pass it as 3rd arg.

**Comment by AnthonyMusgrove** [comment]
I've fixed this one too mate, thank you.  You no longer need to specify an empty CustomHeaderBuilder for it to function correctly.  Omit this parameter and the requests will use default headers. :)  (WIll be available for release tonight)

**Comment by AnthonyMusgrove** [comment]
That's all done mate, up on Emby catalog now v3.0.4.4
