### ISSUE TITLE
Incorrect context values for _onAuthenticationFailed

### ISSUE THREAD

**Issue by Slugger** [AnthonyMusgrove/Emby-ScripterX#39]
**Describe the bug**
In the context for this event, the `%user.id%` token is always set to 0, even for user ids that exist.

**To Reproduce**
1. Install package with _onAuthenticationFailed handler
2. Trigger the handler
3. View the received context

**Expected behavior**
The `%user.id%` token is set based on the username received.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnthonyMusgrove** [comment]
I think this is the emby default maye, I shall follow it up and let you know
