### ISSUE TITLE
onLibraryScanComplete - events for an aborted/failed Library scan 

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#4]
**Describe the solution you'd like**
Some information regarding the scan - ie was it aborted, did it fail?  Possibly an onFailedLibraryScan event, etc

**Comment by Penkethboy** [comment]
see issue #23

**Comment by AnthonyMusgrove** [comment]
Closed this issue and linking to issue #23  :)
