### ISSUE TITLE
_onAuthenticationSuccess is never called

### ISSUE THREAD

**Issue by Slugger** [AnthonyMusgrove/Emby-ScripterX#40]
**Describe the bug**
When a user logs in successfully, the `_onAuthenticationSuccess()` handler from a package is never called.

**To Reproduce**
1. Install a package with the `_onAuthenticationSuccess()` handler defined
2. Trigger the event
3. View debug logs, see that package event handler wasn't called

**Expected behavior**
The event handler from my package should be called.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by AnthonyMusgrove** [comment]
Thank you for reporting this one mate.  This was my issue.  The invoker command was accidentally mis-typed as '_onAuthenticatedSuccess', I've now fixed this and it is now 'onAuthenticationSuccess' and functions as expected:

function _onAuthenticationSuccess(context)
{
	ScripterX.Log.Info("Successful login by " + context.Token("%username%").value);
}

now yields:

2020-06-21 21:55:08.668 Info Emby ScripterX: 8b91c4d0-66f2-47c8-9471-ae9c741d6b6f: Successful login by Anthony

This will be released in v3.0.4.6 tonight.  v3.0.4.5 introduces Package API functions (check out the wiki for info: https://wiki.emby-scripterx.info/books/packages/page/api-extensions)
