### ISSUE TITLE
ScripterX now supports two additional context libraries;

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#41]
Please check out the wiki for more information;

ScripterX.Api.Register, ScripterX.Api.Unregister, ScripterX.Include.Script

<strong>Packages</strong>
* Introduced API extensions.  This new feature is an amazing way to extend your Emby API without having to write
a plugin to do so.  In your package you can 'register' and 'unregister' your own Package API commands that will
direct to a defined callback when they're called from the Emby API.  For more information - please see the
ScripterX wiki page https://wiki.emby-scripterx.info/books/packages/page/api-extensions

<strong>Packages</strong>
* ScripterX now has the ability to include additional scripts in your package with the ScripterX.Include.Script()
function.  Please see https://wiki.emby-scripterx.info/books/packages/page/including-other-script-files-in-your-package
for more information.

**Comment by Slugger** [comment]
Liking the include functionality.  I've been debating on what to do, wait for integration with Node.js, which has imports already or just go for it with one massive script using the current framework.  This makes it a little easier to design something with multiple files.

The api extension is an interesting idea.  I don't have a use case for it myself right away, but I can see it as an interesting option should a use case present itself.
