### ISSUE TITLE
Wiki not available

### ISSUE THREAD

**Issue by vekerdyb** [AnthonyMusgrove/Emby-ScripterX#49]
**Describe the bug**
Wiki is not available on the links.
https://wiki.emby-scripterx.info/ redirects to https://www.hunter3dprinting.com.au/

**To Reproduce**
1. Go to https://www.hunter3dprinting.com.au/
2. See TLS error / redirection to a different site.

**Expected behavior**
See the documentation for ScripterX

**Comment by AnthonyMusgrove** [comment]
Thank you for reporting this issue!  Our apologies, our project was idle for some time, project has been restored and a new domain has been registered - therefore the wiki is now available again at https://wiki.emby-scripterx.com (instead of .info)

Thank you!
