### ISSUE TITLE
Interpreter error

### ISSUE THREAD

**Issue by sasagr** [AnthonyMusgrove/Emby-ScripterX#50]
I m not sure what I m doing wrong but when I m trying to add an .sh script and choose /bin/bash interpreter I m seeing an exclamation mark.

I m seeing it whatever interpreter I choose actually.

My server is running on a raspberry with Debian
![ss](https://user-images.githubusercontent.com/3427877/128594385-71319bbd-b04c-4bd5-84d1-062470e6bb9f.png)

**Comment by AnthonyMusgrove** [comment]
Hi @sasagr, thank you for your query!  Could you please try updating to the latest version (v3.0.5.2), and ensure you clean your browser cache / history before trying again.  Please let me know if there's any further issues!

**Comment by sasagr** [comment]
ok, I managed to add the interpreter.
I set the scrpterX to run an .sh upon adding a Movie item type and nothing is happening.
Here my script and and a link to the log:
#!/bin/bash
echo "Test" >> /home/pi/td.log
cd /home/pi/Trailer-Downloader && python3 download_all.py --directory "/home/pi/RD/Movies" >> /home/pi/td.log &

https://pastebin.com/4eXzdZuF

my td.log file did not change

**Comment by sasagr** [comment]
it worked. It was a permission issue! (as usual)

**Comment by AnthonyMusgrove** [comment]
Awesome, thank you mate for your response.  I just checked your log and noticed the error, permission issue is a perfect, easy outcome, thank you again! 

System.ComponentModel.Win32Exception: System.ComponentModel.Win32Exception (2): No such file or directory
