### ISSUE TITLE
Python interepreter missing

### ISSUE THREAD

**Issue by sasagr** [AnthonyMusgrove/Emby-ScripterX#51]
I don’t see the python interpreter listed though I can probably type it myself as usr/local/bin. 
I don’t find also examples of .py scripts and I have no idea of how to call the expected parameters to use in the python. 
can you pls give me an example?

thanks

**Comment by AnthonyMusgrove** [comment]
Hi @sasagr - sure I can create an example for you for python.  I'll post the link to it in these comments, just screen capturing it all now.

**Comment by AnthonyMusgrove** [comment]
@sasagr  - please check out https://wiki.emby-scripterx.com/books/scripting-tutorials/page/media-playback-example-python
