### ISSUE TITLE
About emby running sh scripts

### ISSUE THREAD

**Issue by Qliangw** [AnthonyMusgrove/Emby-ScripterX#56]
## add `/bin/sh` 
There is no `/bin/bash` in emby's official docker environment,Can you add the `/bin/sh` command
![微信图片_20220221162724](https://user-images.githubusercontent.com/22791711/154916509-df6c741b-3e6e-435e-a457-055ae514b55b.png)

Looking forward to your support, thanks!

**Comment by AnthonyMusgrove** [comment]
H @Qliangw, I can add it to the list!   You can also manually type it in :)

**Comment by AnthonyMusgrove** [comment]
Hi again @Qliangw, just letting you know that I've added /bin/sh for the next release!

![image](https://user-images.githubusercontent.com/55648663/163852439-d29c9bca-edb5-472e-8999-24fe6c381470.png)

**Comment by AnthonyMusgrove** [comment]
I've also addressed your needs in the next version, I've added an option to the dropdown called sendmessage:sessionid - you can use it whereever %session.id% is available.  It works awesome.

![image](https://user-images.githubusercontent.com/55648663/163858407-34092a6d-b2d3-4c9d-80fb-6f95f08d80b9.png)

![image](https://user-images.githubusercontent.com/55648663/163858451-dc6eb5c2-7008-487c-8e0c-624529c72a7b.png)

**Comment by AnthonyMusgrove** [comment]
I'll also put it up on the wiki when I can, and the support forum includes it on page 22 @Qliangw

**Comment by Qliangw** [comment]
Thank you very much for the new features added to the software and for your attention！

**Comment by AnthonyMusgrove** [comment]
You're more than welcome @Qliangw!  Thank you so much for your suggestions, they're very much appreciated <3
