### ISSUE TITLE
onPlaybackStart event does not pass Tuner instance if %item.type% is LiveTvChannel

### ISSUE THREAD

**Issue by chrishammond1969** [AnthonyMusgrove/Emby-ScripterX#59]
**Is your feature request related to a problem? Please describe.**
I am attempting to run a script when a LiveTV channel is selected for Play from a M3U tuner. My current implementation is fine when I have only one tuner, as the script can target the specific device need for channel changing. However, when I have two tuners, the onPlaybackStart event DOES pass the channel name via the %item.name% variable but cannot/does not pass the specific tuner used. So the script cannot discern which device to send the channel change to.

**Describe the solution you'd like**
For the onLiveTvRecordingStart event, these variables are passed: %recording.channel.number% %recording.tuner.type%  %recording.tuner.url%. If these variables were available as maybe: %playback.channel.number% %playback.tuner.type%  %playback.tuner.url%, then that would solve which tuner was selected for playback

**Comment by AnthonyMusgrove** [comment]
Thank you for this information mate - I'm adding this to the list for testing for the new Live TV implementation/libraries

**Comment by AnthonyMusgrove** [comment]
Just an update on this one - still working on getting the tuner information based on the events using the new LiveTV libraries.  It's a work in progress and a very high priority.
