### ISSUE TITLE
Token substitution not occuring for %item.library.name% "onPlaybackStart", playing a tv episode

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#6]
**Describe the bug**
tested on v2.1.8

**Comment by Penkethboy** [comment]
this is also happening on
itemadded
itemupdated
itemremoved
playbackstart
playbackstop

it used to work as have logs from a couple of days ago where adding a series have the library.name

Also for Playbackstart and PlayBackStop library.type is not returning anything

**Comment by AnthonyMusgrove** [comment]
Thank you mate, this is now resolved, and will be included in the upcoming release :)

It was a system-wide referencing issue which is now resolved :)

START Library Name: %item.library.name% - Library Type: %item.library.type%

Emby ScripterX: onPlaybackStart: START Library Name: Music - Library Type: music
Emby ScripterX: onPlaybackStart: START Library Name: TV - Library Type: tvshows
Emby ScripterX: onPlaybackStart: START Library Name: Movies - Library Type: movies
