### ISSUE TITLE
LiveTV Rewire

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#61]
Rewire of LiveTV functionality to ensure all functionality works according to specification.

* internals of Emby Core have changed significantly and a rewire of certain ScripterX functionality is required for the plugin moving forward for the Emby Beta 4.7+ version and above.

**Comment by AnthonyMusgrove** [comment]
We're getting there with the new LiveTV core.

`STARTED %recording.channel.id% %recording.channel.name% %recording.channel.number% %recording.channel.mediatype% %recording.timer.id% %recording.name% %recording.path% %recording.program.id% %recording.show.id% %recording.episode.number% %recording.episode.title% %recording.series.id% %recording.season.number% %recording.productionyear% %recording.date.start.utc% %recording.date.end.utc% %recording.date.start% %recording.date.end% %recording.prepadsecs% %recording.postpadsecs% %recording.iskids% %recording.islive% %recording.ismanual% %recording.ismovie% %recording.isnew% %recording.isnews% %recording.isprepaddingrequired% %recording.ispostpaddingrequired% %recording.ispremiere% %recording.isprogramseries% %recording.isrepeat% %recording.isseries% %recording.issports% %server.name% %server.port.local.http% %server.port.local.https% %server.port.public.http% %server.port.public.https% %server.version% %server.platform.os% %server.platform.osver% %server.platform.uptime% %scripterx.version% %scripterx.version.major% %scripterx.version.revision% %scripterx.version.minor% %scripterx.version.build%`

produces:

`ALL VARS = STARTED 6707 Peach 10 Video e2e926c9d00c4573a66c105e42dd596e The Big Bang Theory C:\Users\Hunter3DPrinting\AppData\Roaming\Emby-Server\programdata\data\livetv\recordings\The Big Bang Theory\The Big Bang Theory 2022_04_18_22_24_47.ts 19840 %recording.show.id%  %recording.episode.title% 7db878918f368de5a24c9349d19eefbd   18/04/2022 12:24:47 PM +00:00 18/04/2022 12:50:50 PM +00:00 18/04/2022 10:24:47 PM 18/04/2022 10:50:50 PM 0 0 False False True False False False False False False True False True False H3DP-LASERPC 8096 8920 8096 8920 4.7.0.35 Win32NT Microsoft Windows 10.0.19042 1d 21h 37m 33s  4.0.0.1 4 1 0 0 
ALL VARS = ENDED 6707 Peach 10 Video e2e926c9d00c4573a66c105e42dd596e The Big Bang Theory C:\Users\Hunter3DPrinting\AppData\Roaming\Emby-Server\programdata\data\livetv\recordings\The Big Bang Theory\The Big Bang Theory 2022_04_18_22_24_47.ts 19840 %recording.show.id%  %recording.episode.title% 7db878918f368de5a24c9349d19eefbd   18/04/2022 12:24:47 PM +00:00 18/04/2022 12:50:50 PM +00:00 18/04/2022 10:24:47 PM 18/04/2022 10:50:50 PM 0 0 False False True False False False False False False True False True False H3DP-LASERPC 8096 8920 8096 8920 4.7.0.35 Win32NT Microsoft Windows 10.0.19042 1d 21h 37m 48s  4.0.0.1 4 1 0 0 `

Still a few things to figure out, like being able to locate the tuner responsible for the recording again, the old way of doing things I could locate it via some searching, so I'm prodding for the newer ways to do so!

**Comment by Skitals** [comment]
Dang, I've been trying to get onLiveTV working and didn't realize it doesn't work on current stable emby. With emby 4.7.10.0 and ScripterX 3.0.5.5 I get:

`SimpleInjector.ActivationException: SimpleInjector.ActivationException: No registration for type ScripterXController could be found and an implicit registration could not be made. Could not load type 'MediaBrowser.Controller.LiveTv.ILiveTvService' from assembly 'MediaBrowser.Controller, Version=4.7.10.0, Culture=neutral, PublicKeyToken=null'.`

All I "need" is %recording.name% to be able to get real-time comskip running.

Is this still being worked on?
