### ISSUE TITLE
ItemAdded is not fired for Trailers, Series Trailer 

### ISSUE THREAD

**Issue by AnthonyMusgrove** [AnthonyMusgrove/Emby-ScripterX#9]
**Describe the bug**
Specials are ok with Series as seen as a Season 0
When an item is Updated - Trailers are seen - but do not show the library name

**Comment by Penkethboy** [comment]
Also - extras in an extras folder for a movie - do not fire itemadded

but do for itemupdated, itemremoved

**Comment by AnthonyMusgrove** [comment]
This should also be rectified with regard to the parent and path being null and not having a library assigned to them.  If further testing is required please feel free to reopen the issue :) kindest regards
